openapi: 3.0.0
info:
   title: "Transactions API"
   version: 1.0.0

paths:
  /api/transaction/sum:
    get:
      operationId: calculateSum
      parameters:
        - name: to
          in: query
          required: true
          schema:
            type: string
        - name: from
          in: query
          required: true
          schema:
            type: string
      responses:
        200:
          description: sum
          content:
            application/json:
              schema:
                type: number
                format: double
  /api/transactions:
    get:
      operationId: getTransactionsList
      parameters:
        - name: from
          in: query
          description: Matches exactly the email from
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: to
          in: query
          description: Matches exactly the email to
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
        - name: message
          in: query
          description: Matches exactly or a part of message field
          style: form
          explode: false
          schema:
            type: array
            items:
              type: string
      responses:
        200:
          description: Ok
          content:
            application/json:    
              schema:
                type: array
                items:                
                  $ref: "./Transaction.yaml"
        500:
          description: Something wrong happened
    put:
      operationId: putTransaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              anyOf:
                - $ref: "./Transaction.yaml"
                - type: object
                  properties:
                    batch_name:
                      type: string
                    batch:
                      type: array
                      items:
                        $ref: "./Transaction.yaml"
                  required:
                    - batch
      responses:
        200:
          description: Ok
        500:
          description: Something wrong happened

components:
  schemas: {}
